name: Build and Publish Docker image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      DOCKER_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Uncomment and adjust the following if you want to run Go tests/builds
      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: ${{ vars.GO_VERSION }}
      #
      # - name: Install dependencies
      #   run: go mod download
      #   working-directory: ./src
      #
      # - name: Run tests
      #   run: go test -v ./...
      #   working-directory: ./src
      #
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: go-test-results
      #     path: src

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build images with Docker Compose
        run: |
          docker compose build --build-arg IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} --build-arg IMAGE_TAG=${{ env.DOCKER_IMAGE_TAG }}

      - name: Scan Docker image for vulnerabilities
        id: trivy_scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --severity HIGH,CRITICAL --exit-code 1 --format table ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Check for vulnerabilities
        if: failure()
        run: |
          echo "High or critical severity vulnerabilities found. Failing the pipeline."
          exit 1

      - name: Push images to Docker Hub
        run: |
          docker compose push

      - name: Stop and remove Docker Compose services
        if: always()
        run: docker compose down
