name: Build and Publish Docker image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      DOCKER_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Uncomment and adjust the following if you want to run Go tests/builds
      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: ${{ vars.GO_VERSION }}
      #
      # - name: Install dependencies
      #   run: go mod download
      #   working-directory: ./src
      #
      # - name: Run tests
      #   run: go test -v ./...
      #   working-directory: ./src
      #
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: go-test-results
      #     path: src

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Scan Docker image for vulnerabilities
        uses: docker/scout-action@v1
        with:
          image: ${{ env.DOCKER_IMAGE_NAME }}:latest
